/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProjectStatus = IDL.Variant({
  'done' : IDL.Null,
  'inProgress' : IDL.Null,
  'approvalPending' : IDL.Null,
});
export const Time = IDL.Int;
export const PositionalComment = IDL.Record({
  'id' : IDL.Nat,
  'xPercentage' : IDL.Float64,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'yPercentage' : IDL.Float64,
});
export const CreativeProject = IDL.Record({
  'id' : IDL.Text,
  'status' : ProjectStatus,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'commentIdCounter' : IDL.Nat,
  'amazonUploadTimestamp' : IDL.Opt(IDL.Nat),
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'positionalComments' : IDL.Vec(PositionalComment),
  'completionTimestamp' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPositionalComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'createProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Vec(ExternalBlob),
        ProjectStatus,
      ],
      [],
      [],
    ),
  'deletePositionalComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(CreativeProject)], ['query']),
  'getPositionalComments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PositionalComment)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Text], [CreativeProject], ['query']),
  'getProjectsByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CreativeProject)],
      ['query'],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Vec(ExternalBlob),
        ProjectStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProjectStatus = IDL.Variant({
    'done' : IDL.Null,
    'inProgress' : IDL.Null,
    'approvalPending' : IDL.Null,
  });
  const Time = IDL.Int;
  const PositionalComment = IDL.Record({
    'id' : IDL.Nat,
    'xPercentage' : IDL.Float64,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'yPercentage' : IDL.Float64,
  });
  const CreativeProject = IDL.Record({
    'id' : IDL.Text,
    'status' : ProjectStatus,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'commentIdCounter' : IDL.Nat,
    'amazonUploadTimestamp' : IDL.Opt(IDL.Nat),
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'positionalComments' : IDL.Vec(PositionalComment),
    'completionTimestamp' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPositionalComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'createProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Vec(ExternalBlob),
          ProjectStatus,
        ],
        [],
        [],
      ),
    'deletePositionalComment' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(CreativeProject)], ['query']),
    'getPositionalComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PositionalComment)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Text], [CreativeProject], ['query']),
    'getProjectsByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CreativeProject)],
        ['query'],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Vec(ExternalBlob),
          ProjectStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };