/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreativeProject {
  'id' : string,
  'status' : ProjectStatus,
  'title' : string,
  'creator' : Principal,
  'commentIdCounter' : bigint,
  'amazonUploadTimestamp' : [] | [bigint],
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'positionalComments' : Array<PositionalComment>,
  'completionTimestamp' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface PositionalComment {
  'id' : bigint,
  'xPercentage' : number,
  'text' : string,
  'timestamp' : bigint,
  'yPercentage' : number,
}
export type ProjectStatus = { 'done' : null } |
  { 'inProgress' : null } |
  { 'approvalPending' : null };
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPositionalComment' : ActorMethod<
    [string, string, number, number],
    undefined
  >,
  'createProject' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      Array<ExternalBlob>,
      ProjectStatus,
    ],
    undefined
  >,
  'deletePositionalComment' : ActorMethod<[string, bigint], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<CreativeProject>>,
  'getPositionalComments' : ActorMethod<[string], Array<PositionalComment>>,
  'getProject' : ActorMethod<[string], CreativeProject>,
  'getProjectsByCreator' : ActorMethod<[Principal], Array<CreativeProject>>,
  'updateProject' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      Array<ExternalBlob>,
      ProjectStatus,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];